---
title: "IPCA - 09/03"
author: "Observatório Macroeconômico da UFABC Finance"
date: "29/03/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sidrar)
library(tidyverse)
library(tstools)
library(BETS)
library(ggthemes)
library(scales)
library(lubridate)
library(timetk)
library(knitr)
library(seasonal)
```


## O que é o IPCA


## Como ele medido



## Alerta




#### informações rápidas para escrevermos

```{r message=FALSE, warning=FALSE, include=FALSE}
### Inflação cheia

ipca <-
  '/t/1737/n1/all/v/2266/p/all/d/v2266%2013' %>%
  get_sidra(api=.) %>%
  mutate(date = parse_date(`Mês (Código)`, format="%Y%m")) %>%
  rename(indice = Valor) %>%
  mutate(inflacao_mensal = (indice/lag(indice,1)-1)*100,
         inflacao_anual = (indice/lag(indice,12)-1)*100) %>%
  select(date, indice, inflacao_mensal, inflacao_anual) %>%
  as_tibble()

```

```{r echo=FALSE, fig.height=4, fig.width=8, message=FALSE, warning=FALSE, out.width="1\\linewidth", results='markup', size='tiny'}


ipca %>%
  select(date, inflacao_mensal, inflacao_anual) %>%
 `colnames<-`(c('Data','Inflação mensal', 'Inflação anual')) %>%
  tail(n= 24) %>%
  kable(digits = 2)

```




```{r message=FALSE, warning=FALSE, include=FALSE}
## coletando a inflação por grupo

variacao <-
  '/t/7060/n1/all/v/63/p/all/c315/7170,7445,7486,7558,7625,7660,7712,7766,7786/d/v63%202' %>%
  get_sidra(api=.) %>%
  mutate(date = parse_date(`Mês (Código)`, format="%Y%m")) %>%
  select(date, "Geral, grupo, subgrupo, item e subitem", Valor) %>%
  pivot_wider(names_from = "Geral, grupo, subgrupo, item e subitem", values_from= Valor)

```


```{r}
variacao %>%
  kable(digits = 2)
```



```{r include=FALSE}
## coletando o peso de cada grupo
peso <-
  "/t/7060/n1/all/v/66/p/all/c315/7170,7445,7486,7558,7625,7660,7712,7766,7786/d/v66%204" %>%
  get_sidra(api=.) %>%
  mutate(date = parse_date(`Mês (Código)`, format = "%Y%m")) %>%
  select(date, "Geral, grupo, subgrupo, item e subitem", Valor) %>%
  pivot_wider(names_from = "Geral, grupo, subgrupo, item e subitem", values_from = Valor)
```

```{r}
peso%>%
  kable(digits = 2)
```

```{r include=FALSE}
# construindo a tabela de contribuição mensal de cada grupo no IPCA
contribuicao <- ((variacao[,-1]* peso[,-1])/ 100) %>%
  mutate(date= variacao$date) %>%
  select(date, everything())
  
```

```{r}
contribuicao %>%
  kable(digits = 2)
  

```

```{r}
 teste <- contribuicao %>% 
  gather()
  
```


## Insumos para o gráfico

```{r}
ipca <-
  '/t/1737/n1/all/v/2266/p/all/d/v2266%2013' %>%
  get_sidra(api=.) %>%
  mutate(date = parse_date(`Mês (Código)`, format="%Y%m")) %>%
  rename(indice = Valor) %>%
  mutate(inflacao_mensal = (indice/lag(indice,1)-1)*100,
         inflacao_anual = (indice/lag(indice,12)-1)*100) %>%
  select(date, indice, inflacao_mensal, inflacao_anual) %>%
  as_tibble()

```


```{r message=FALSE, warning=FALSE, include=FALSE}

### Núcleos de Inflação

codes = c(4466,11426,11427,16121,16122, 27838, 27839)
nucleos = BETSget(codes, from='2012-01-01', data.frame=T)
data_nucleos = matrix(NA, nrow=nrow(nucleos[[1]]),
                      ncol=length(codes))
for(i in 1:length(codes)){
  data_nucleos[,i] = t(nucleos[[i]]$value)
}

colnames(data_nucleos) = c('ipca_ms', 'ipca_ma', 'ipca_ex0',
                           'ipca_ex1', 'ipca_dp', 'ipca_ex2',
                           'ipca_ex3')

nucleos_vm =
  data_nucleos %>%
  as_tibble() %>%
  mutate(date = nucleos[[1]]$date) %>%
  select(date, everything())

nucleos_12m = 
  data_nucleos %>%
  ts(start=c(2012,01), freq=12) %>%
  acum_p(12) %>%
  as_tibble() %>%
  mutate(date = nucleos[[1]]$date) %>%
  select(date, everything()) %>%
  drop_na()


```


```{r echo=FALSE, message=FALSE, warning=FALSE}

## plotando os núcleos

nucleos_12m %>%
  filter(date >'2019-12-01') %>%
  gather(variavel, valor, -date) %>%
  ggplot(aes(x=date, y=valor, colour=variavel))+
  geom_line(size=1) +
  facet_wrap(~variavel, scales='free')+
  theme_clean() +
  theme(legend.position = 'none', axis.text.x = element_text(angle=90), legend.background = element_blank(), legend.title = element_blank())+
  scale_x_date(labels = date_format("%b"), date_breaks = "1 month") +
   coord_cartesian(xlim = c(as.Date("2020-01-01"),as.Date("2020-11-01")))+
  labs(x='', y='%',
       title = "Inflação acumulada em 12 meses de cada núcleo do IPCA",
       caption='Fonte: IBGE - Elaboração: UFABC Finance')


```


```{r include=FALSE}

### Metas de Inflação

meta = c(rep(4.5,12*7-11), rep(4.25, 12), rep(4, month(Sys.time(),label = F)))
meta_max = c(rep(4.5+2,12*5-11), rep(4.5+1.5,12*2),
             rep(4.25+1.5,12), rep(4+1.5, month(Sys.time(),label = F)))
meta_min = c(rep(4.5-2,12*5-11), rep(4.5-1.5,12*2),
             rep(4.25-1.5,12), rep(4-1.5, month(Sys.time(),label = F)))
data_meta = 
  tibble(date = seq(as.Date('2013-12-01'), Sys.Date(),
                    by='1 month'),
         meta_min = meta_min,
         meta = meta,
         meta_max = meta_max)


```

# Gráfico principal

```{r echo=FALSE}
## Plotanto


 filter(ipca, date > '2016-12-01') %>%
  ggplot(aes(x=date))+
  geom_line(aes(y=inflacao_anual, colour='IPCA'),
            size=1.5) +
  geom_line(data=na.omit(nucleos_12m), 
            aes(y=rowMeans(nucleos_12m[,-1]),
                                  colour='Média dos Núcleos'),
            size=1.5)+
  geom_ribbon(data=data_meta,
              aes(ymin=meta_min, ymax=meta_max), 
              colour='grey70', alpha=0.1, size=1) +
    geom_line(data=data_meta,
            aes(y=meta, colour='Meta'), size=1, linetype='dashed' )+
    scale_colour_manual('',
                      values=c('IPCA'='#0099ff',
                               'Média dos Núcleos' = '#00cc66',
                               'Meta'='red'))+
  geom_label( data=ipca%>% filter(date == "2021-02-01"), # Filter data first
    aes(label= round(inflacao_anual,1), y=inflacao_anual))+
  geom_label(data = nucleos_12m %>% filter(date == "2021-02-01"),
             aes(label= round(last(rowMeans(nucleos_12m[,-1])),1),y= last(rowMeans(nucleos_12m[,-1]))))+
  theme_clean()+
  scale_x_date(labels = date_format("%b/%y"), date_breaks = "2 month") +
  coord_cartesian(xlim = c(as.Date("2018-01-01"),as.Date("2021-02-01")))+
  theme(axis.text.x = element_text(angle=90), legend.position = 'top', legend.background = element_blank())+
  labs(x='', y='%', 
       title='Inflação e as metas do Banco Central ',
       caption='Fonte: IBGE - Elaboração: UFABC Finance')

  
```





